name: Build and Deploy

on:
  push:
    branches:
      - 09

jobs:

  format-lint-test:
    runs-on: ubuntu-latest  

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Check formatting
        run: cargo fmt -- --check